# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'impulse_challenge' do

  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'


  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for impulse_challenge

  target 'impulse_challengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'impulse_challengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
